dist: trusty
language: python
os: linux

jobs:
    include:
        - python: 2.7
          env: TOXENV=py27
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
          dist: xenial

install:
    - travis_retry pip install tox

script:
    - tox
